USE [Restauracja]
GO

/****** Object:  Table [dbo].[TABELA_JEDNOSTKA]    Script Date: 09.05.2022 22:55:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TABELA_JEDNOSTKA](
	[Id_Jednostka] [int] NOT NULL,
	[Jednostka] [nchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Jednostka] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

