USE [Restauracja]
GO

/****** Object:  Table [dbo].[TABELA_RODZAJ]    Script Date: 09.05.2022 22:55:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TABELA_RODZAJ](
	[Id_Rodzaj] [int] NOT NULL,
	[Rodzaj] [nchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Rodzaj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

